import csv
import os

extraartists = [
    'Rosalía',
    'Bad Bunny',
    'J Balvin',
    'Daddy Yankee',
    'Ozuna',
    'Enrique Iglesias',
    'Shakira',
    'Maluma',
    'Juanes',
    'Carlos Vives',
    'Manuel Turizo',
    'Ana Guerra',
    'Pablo Alborán',
    'Aitana',
    'David Bisbal',
    'Alejandro Sanz',
    'Beret',
    'Natti Natasha',
    'Karol G',
    'Sebastián Yatra',
    'Morat',
    'C. Tangana',
    'Becky G',
    'Sebastián Yatra',
    'Manuel Carrasco',
    'Antonio Orozco',
    'Vanesa Martín',
    'Mon Laferte',
    'Camilo',
    'Reik',
    'Amaia',
    'Danna Paola',
    'Tini',
    'Mau y Ricky',
    'Piso 21',
    'Greeicy',
    'Lola Índigo',
    'Cali y El Dandee',
    'India Martínez',
    'Morat',
    'Leiva',
    'Rozalén',
    'Rozalén',
    'Miriam Rodríguez',
    'La Oreja de Van Gogh',
    'Pablo López',
    'Leire Martínez',
    'Fito & Fitipaldis',
    'Amaral',
    'Malú',
    'Rozalén',
    'Melendi',
    'Fangoria',
    'Taburete',
    'Marta Sánchez',
    'La Casa Azul',
    'Estopa',
    'Melendi',
    'Los Secretos',
    'Maná',
    'Andrés Calamaro',
    'Rosana',
    'Los Ángeles Azules',
    'Hombres G',
    'Natalia Lafourcade',
    'Jarabe de Palo',
    'Chayanne',
    'Laura Pausini',
    'Ana Belén',
    'Rauw Alejandro',
    'Carlos Baute',
    'La Quinta Estación',
    'La Sonora Dinamita',
    'Los del Río',
    'La Mala Rodríguez',
    'Miguel Bosé',
    'Los Auténticos Decadentes',
    'Sergio Dalma',
    'Alex Ubago',
    'José Luis Perales',
    'Julieta Venegas',
    'Ricardo Montaner',
    'Café Tacvba',
    'Jarabe de Palo',
    'Rosario Flores',
    'Los Ángeles Negros',
    'Juan Luis Guerra',
    'Pablo Milanes',
    'Vicente García',
    'Diego Torres',
    'Roser',
    'Natalia Jiménez',
    'Thalía',
    'Ricky Martin',
    'Juan Magán',
    'Juan Gabriel',
    'Los Panchos',
    'Ana Torroja',
    'Mocedades',
    'Los Bukis',
    'Ricky Martin',
    'Gente de Zona',
    'Aventura',
    'Bacilos',
    'Joan Manuel Serrat',
    'Dyango',
    'Moncho',
    'Raphael',
    'José José',
    'Juanes',
    'Jarabe de Palo',
    'Joaquín Sabina',
    'Alejandro Fernández',
    'Julio Iglesias',
    'Luis Fonsi',
    'José Luis Rodríguez',
    'Los Tigres del Norte',
    'Los Temerarios',
    'Roberto Carlos',
    'Yuri',
    'Jenni Rivera',
    'Pedro Infante',
    'Rocío Dúrcal',
    'Lola Flores',
    'José Feliciano',
    'Marc Anthony',
    'Ricardo Arjona',
    'Gilberto Santa Rosa',
    'Luis Miguel',
    'Marco Antonio Solís',
    'Camilo Sesto',
    'Raphael',
    'Julio Iglesias',
    'David Bustamante',
    'Antonio José',
    'Bustamante',
    "Rosalía",
    "Bad Bunny",
    "J Balvin",
    "Duki",
    "Anuel AA",
    "C. Tangana",
    "Khea",
    "Trueno",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Duki",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Bhavi",
    "Ozuna",
    "Nicky Jam",
    "Farruko",
    "Maluma",
    "Jhay Cortez",
    "Sech",
    "Myke Towers",
    "Arcángel",
    "Noriel",
    "Brytiago",
    "Jon Z",
    "Alex Rose",
    "Rauw Alejandro",
    "Darell",
    "Casper Mágico",
    "Ñengo Flow",
    "Wisin",
    "Yandel",
    "Tito El Bambino",
    "Zion & Lennox",
    "Don Omar",
    "Daddy Yankee",
    "Residente",
    "Natti Natasha",
    "Karol G",
    "Becky G",
    "Anitta",
    "Greeicy",
    "Lali",
    "Danna Paola",
    "Paloma Mami",
    "Aitana",
    "Lérica",
    "Rozalén",
    "Ana Guerra",
    "Nathy Peluso",
    "Tomasa del Real",
    "La Zowi",
    "Kaydy Cain",
    "Yung Beef",
    "Yung Sarria",
    "Kidd Keo",
    "Pimp Flaco",
    "Kidd Tetoon",
    "Rels B",
    "Natos y Waor",
    "Ayax",
    "Prok",
    "Hens",
    "Cruz Cafuné",
    "Recycled J",
    "Dellafuente",
    "Shinova",
    "Rayden",
    "Sharif",
    "Costa",
    "Piezas",
    "Nueva Vulcano",
    "La Raíz",
    "SFDK",
    "Foyone",
    "Fernandocosta",
    "Jade",
    "Kaze",
    "Nach",
    "Mala Rodríguez",
    "Natos y Waor",
    "ZPU",
    "Duo Kie",
    "Rapvívoros",
    "Shotta",
    "Fyahbwoy",
    "SFDK",
    "Suite Soprano",
    "Hombres de Honor",
    "Juancho Marqués",
    "Kase.O",
    "Soge Culebra",
    "Mishi",
    "Arce",
    "Gordo Master",
    "El Chojin",
    "Rapsusklei",
    "Zatu",
    "Sharif",
    "MDE Click",
    "Santo Niño",
    "Ayax",
    "Arkano",
    "Recycled J",
    "ToteKing",
    "Narco",
    "Toteking",
    "Chuty",
    "Skone",
    "Blon",
    "Bnet",
    "Force",
    "Zasko Master",
    "Sweet Pain",
    "Mister Ego",
    "Hander",
    "Elio Toffana",
    "Lopes",
    "Chirie Vegas",
    "Nasta",
    "Juancho Marqués",
    "Shotta",
    "Gata Cattana",
    "Costa",
    "Zetazen",
    "Maka",
    "Ghemon",
    "Natos y Waor",
    "Rels B",
    "Niva",
    "Choclock",
    "Lone",
    "Rels Beats",
    "Foyone",
    "Alizzz",
    "Yung Beef",
    "Kaydy Cain",
    "Khaled",
    "Vicente El Vizio",
    "Bejo",
    "Kase.O",
    "Iván Nieto",
    "Rayden",
    "Sharif",
    "Rafael Lechowski",
    "Falsalarma",
    "ToteKing",
    "El Chojin",
    "Nega",
    "Zatu",
    "SFDK",
    "Shinoflow",
    "Rapsusklei",
    "ZPU",
    "Porta",
    "Suite Soprano",
    "Duo Kie",
    "Piezas",
    "Natos y Waor",
    "Chuty",
    "Skone",
    "Bnet",
    "Arkano",
    "Yung Beef",
    "Kidd Keo",
    "C. Tangana",
    "Duki",
    "Ysy A",
    "ECKO",
    "Trueno",
    "DrefQuila",
    "Khea",
    "Cazzu",
    "Duki",
    "Neo Pistea",
    "LIT Killah",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Duki",
    "Duki",
    "Paulo Londra",
    "C. Tangana",
    "Kidd Keo",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Duki",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Duki",
    "C. Tangana",
    "Kidd Keo",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Duki",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Duki",
    "C. Tangana",
    "Kidd Keo",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Duki",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Duki",
    "C. Tangana",
    "Kidd Keo",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Duki",
    "Paulo Londra",
    "Kidd Keo",
    "Ysy A",
    "Dalex",
    "Duki",
    "C. Tangana",
    "Kidd Keo",
    "DrefQuila",
    "Cazzu",
    "Neo Pistea",
    "LIT Killah",
    "Natos y Waor",
    "Ayax",
    "Chuty",
    "Piezas",
    "Babi",
    "Recycled J",
    "Kase.O",
    "Shinoflow",
    "Sharif",
    "Fernandocosta",
    "Rapsusklei",
    "Foyone",
    "Arkano",
    "ToteKing",
    "Nega",
    "Mala Rodríguez",
    "ZPU",
    "El Chojin",
    "SFDK",
    "Costa",
    "Rayden",
    "Lírico",
    "Zetazen",
    "Juancho Marqués",
    "Suite Soprano",
    "Duo Kie",
    "Kidd Keo",
    "Khaled",
    "Gata Cattana",
    "Dharius",
    "Lopes",
    "Elio Toffana",
    "Nasta",
    "El Momo",
    "Shotta",
    "Jerv.agz",
    "Zoo",
    "El Niño Snake",
    "Rafael Lechowski",
    "Soge Culebra",
    "Denom",
    "Capaz",
    "Rapvívoros",
    "Lírico",
    "Narco",
    "Costa",
    "Sharif",
    "Bejo",
    "Al2 El Aldeano",
    "El Jincho",
    "Ruso",
    "Rapvívoros",
    "Sharif",
    "Lírico",
    "Fyahbwoy",
    "C. Tangana",
    "Natos y Waor",
    "Ayax",
    "Rels B",
    "Niva",
    "Hard GZ",
    "Kaze",
    "Xcese",
    "Hens",
    "Mala Juntera",
    "Nasta",
    "Costa",
    "Rafael Lechowski",
    "Falsalarma",
    "Shotta",
    "Rayden",
    "SFDK",
    "ZPU",
    "Natos y Waor",
    "Chuty",
    "Duo Kie",
    "Dharius",
    "Mister Ego",
    "Triple XXX",
    "Arkano",
    "El Chojin",
    "ZPU",
    "Rafael Lechowski",
    "Fyahbwoy",
    "Denom",
    "Capaz",
    "Sharif",
    "Mishii",
    "Shotta",
    "Juancho Marqués",
    "Rapvívoros",
    "Piezas",
    "Narco",
    "Hard GZ",
    "Hens",
    "Kase.O",
    "Rels B",
    "Ayax",
    "Jerv.agz",
    "Natos y Waor",
    "Duo Kie",
    "Lírico",
    "Recycled J",
    "Sharif",
    "Gordo Master",
    "Rapsusklei",
    "Juaninacka",
    "Locus",
    "Foyone",
    "Shinoflow",
    "Rayden",
    "Chuty",
    "Rapvívoros",
    "Arkano",
    "ZPU",
    "Dharius",
    "Ghemon",
    "Mala Juntera",
    "Nicki Nicole",
    "Trym",
    "Richie Hawtin",
    "Rodriguez Jr.",
    "Sasha",
    "Sébastien Léger",
    "Solardo",
    "Solomun",
    "Stefano Noferini",
    "Stephan Bodzin",
    "Steve Bug",
    "Tale Of Us",
    "The Black Madonna",
    "The Martinez Brothers",
    "Tiga",
    "Tim Engelhardt",
    "Tom Trago",
    "Tube & Berger",
    "Veerus",
    "Vini Vici",
    "Worakls",
    "Yotto",
    "Adriatique",
    "Agents Of Time",
    "Andhim",
    "Andrea Oliva",
    "ANNA",
    "Archie Hamilton",
    "Audiojack",
    "Bedouin",
    "Bicep",
    "Black Coffee",
    "Blawan",
    "Booka Shade",
    "Butch",
    "CamelPhat",
    "Caribou",
    "Chris Lake",
    "Claptone",
    "Daniel Avery",
    "Dave Seaman",
    "Denis Sulta",
    "Dixon",
    "DJ Tennis",
    "Dominik Eulberg",
    "Dusky",
    "Eats Everything",
    "Ellen Allien",
    "Erol Alkan",
    "Gardens Of God",
    "Gerd Janson",
    "Gorje Hewek",
    "Gregor Tresher",
    "Guy Gerber",
    "HOSH",
    "I Hate Models",
    "Jamie Jones",
    "Jan Blomqvist",
    "Jeremy Olander",
    "Jon Hopkins",
    "Joris Voorn",
    "Joseph Capriati",
    "Joyhauser",
    "Karenn",
    "KiNK",
    "Kollektiv Turmstrasse",
    "Kölsch",
    "Len Faki",
    "Luttrell",
    "Maceo Plex",
    "Mall Grab",
    "Mano Le Tough",
    "Marcel Dettmann",
    "Marco Carola",
    "Mark Knight",
    "Mathame",
    "Mind Against",
    "Modeselektor",
    "Monolink",
    "Nastia",
    "Nic Fanciulli",
    "Nicole Moudaber",
    "Nina Kraviz",
    "Oxia",
    "Paco Osuna",
    "Patrice Bäumel",
    "Peggy Gou",
    "Rampa",
    "Reinier Zonneveld",
    "Richie Hawtin",
    "Rodriguez Jr.",
    "Sasha",
    "Sébastien Léger",
    "Solardo",
    "Solomun",
    "Stefano Noferini",
    "Stephan Bodzin",
    "Steve Bug",
    "Tale Of Us",
    "The Black Madonna",
    "The Martinez Brothers",
    "Tiga",
    "Tim Engelhardt",
    "Tom Trago",
    "Tube & Berger",
    "Veerus",
    "Vini Vici",
    "Worakls",
    "Yotto",
    "Adam Beyer",
    "Amelie Lens",
    "Âme",
    "ANNA",
    "Artbat",
    "Ben Klock",
    "Black Coffee",
    "Boris Brejcha",
    "Carl Cox",
    "Charlotte de Witte",
    "Chris Liebing",
    "Dixon",
    "Dominik Eulberg",
    "Dubfire",
    "Enrico Sangiuliano",
    "Fatboy Slim",
    "Gorgon City",
    "Guy J",
    "Hernan Cattaneo",
    "Hot Since 82",
    "Jamie Jones",
    "Jeff Mills",
    "Joris Voorn",
    "Joseph Capriati",
    "Kölsch",
    "Laurent Garnier",
    "Maceo Plex",
    "Mano Le Tough",
    "Marcel Dettmann",
    "Marco Carola",
    "Matador",
    "Möwe",
    "Nina Kraviz",
    "Oliver Heldens",
    "Pan-Pot",
    "Paul Kalkbrenner",
    "Peggy Gou",
    "Recondite",
    "Richie Hawtin",
    "Sasha",
    "Solomun",
    "Stephan Bodzin",
    "Tale Of Us",
    "The Martinez Brothers",
    "Tiesto",
    "Âme",
    "Adriatique",
    "Agents Of Time",
    "Andhim",
    "Andrea Oliva",
    "ANNA",
    "Apparat",
    "Archie Hamilton",
    "Audiojack",
    "Bedouin",
    "Bicep",
    "Black Coffee",
    "Blawan",
    "Booka Shade",
    "Butch",
    "CamelPhat",
    "Caribou",
    "Chris Lake",
    "Claptone",
    "Daniel Avery",
    "Dave Seaman",
    "Denis Sulta",
    "Dixon",
    "DJ Tennis",
    "Dominik Eulberg",
    "Dusky",
    "Eats Everything",
    "Ellen Allien",
    "Erol Alkan",
    "Gardens Of God",
    "Gerd Janson",
    "Gorje Hewek",
    "Gregor Tresher",
    "Guy Gerber",
    "HOSH",
    "I Hate Models",
    "Jamie Jones",
    "Jan Blomqvist",
    "Jeremy Olander",
    "Jon Hopkins",
    "Joris Voorn",
    "Joseph Capriati",
    "Joyhauser",
    "Karenn",
    "KiNK",
    "Kollektiv Turmstrasse",
    "Kölsch",
    "Len Faki",
    "Luttrell",
    "Maceo Plex",
    "Mall Grab",
    "Mano Le Tough",
    "Marcel Dettmann",
    "Marco Carola",
    "Mark Knight",
    "Mathame",
    "Mind Against",
    "Modeselektor",
    "Monolink",
    "Nastia",
    "Nic Fanciulli",
    "Nicole Moudaber",
    "Nina Kraviz",
    "Oxia",
    "Paco Osuna",
    "Patrice Bäumel",
    "Peggy Gou",
    "Rampa",
    "Reinier Zonneveld"
]

def read_csv_column(csv_file, column_name):
    data = []  # Array para almacenar los datos de la columna

    relative_path = os.path.join('../data', 'artists.csv')

    # Construct the absolute path to the file
    absolute_path = os.path.abspath(relative_path)
    with open(absolute_path, 'r', encoding='utf-8') as file:
        reader = csv.DictReader(file)

        for row in reader:
            artist = row[column_name]
            data.append(artist)
    num_elementos = len(data) // 20
    return extraartists + data[:num_elementos]

